-- IMANOS Database Schema
-- Complete schema for Supabase PostgreSQL

-- Enable UUID extension
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- ============================================================================
-- USER PROFILES
-- ============================================================================
CREATE TABLE IF NOT EXISTS public.profiles (
  id uuid REFERENCES auth.users ON DELETE CASCADE PRIMARY KEY,
  full_name text,
  avatar_url text,
  madhab text DEFAULT 'hanafi',
  arabic_level text,
  primary_goal text,
  daily_goal_minutes integer DEFAULT 10,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now()
);

-- RLS Policies for profiles
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can view own profile"
  ON public.profiles FOR SELECT
  USING (auth.uid() = id);

CREATE POLICY "Users can update own profile"
  ON public.profiles FOR UPDATE
  USING (auth.uid() = id);

CREATE POLICY "Users can insert own profile"
  ON public.profiles FOR INSERT
  WITH CHECK (auth.uid() = id);

-- ============================================================================
-- QURAN SURAHS  
-- ============================================================================
CREATE TABLE IF NOT EXISTS public.quran_surahs (
  id integer PRIMARY KEY,
  name_arabic text NOT NULL,
  name_english text NOT NULL,
  name_transliteration text,
  revelation_place text,
  total_verses integer NOT NULL,
  created_at timestamp with time zone DEFAULT now()
);

-- Make quran_surahs publicly readable
ALTER TABLE public.quran_surahs ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Surahs are publicly readable"
  ON public.quran_surahs FOR SELECT
  TO public
  USING (true);

-- ============================================================================
-- QURAN VERSES
-- ============================================================================
CREATE TABLE IF NOT EXISTS public.quran_verses (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  surah integer REFERENCES quran_surahs(id) NOT NULL,
  ayah integer NOT NULL,
  text_arabic text NOT NULL,
  text_transliteration text,
  text_english text,
  text_bangla text,
  audio_url text,
  created_at timestamp with time zone DEFAULT now(),
  UNIQUE(surah, ayah)
);

-- Make quran_verses publicly readable
ALTER TABLE public.quran_verses ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Verses are publicly readable"
  ON public.quran_verses FOR SELECT
  TO public
  USING (true);

-- ============================================================================
-- QURAN PROGRESS TRACKING
-- ============================================================================
CREATE TABLE IF NOT EXISTS public.quran_verse_progress (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id uuid REFERENCES auth.users ON DELETE CASCADE NOT NULL,
  surah integer REFERENCES quran_surahs(id) NOT NULL,
  ayah integer NOT NULL,
  completed_at timestamp with time zone DEFAULT now(),
  UNIQUE(user_id, surah, ayah)
);

-- RLS for quran progress
ALTER TABLE public.quran_verse_progress ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can view own progress"
  ON public.quran_verse_progress FOR SELECT
  USING (auth.uid() = user_id);

CREATE POLICY "Users can insert own progress"
  ON public.quran_verse_progress FOR INSERT
  WITH CHECK (auth.uid() = user_id);

-- ============================================================================
-- RECITATION ATTEMPTS (AI Feedback History)
-- ============================================================================
CREATE TABLE IF NOT EXISTS public.recitation_attempts (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id uuid REFERENCES auth.users ON DELETE CASCADE NOT NULL,
  surah integer REFERENCES quran_surahs(id) NOT NULL,
  ayah integer NOT NULL,
  transcription text,
  feedback jsonb,
  score integer,
  audio_url text,
  created_at timestamp with time zone DEFAULT now()
);

-- RLS for recitation attempts
ALTER TABLE public.recitation_attempts ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can view own recitations"
  ON public.recitation_attempts FOR SELECT
  USING (auth.uid() = user_id);

CREATE POLICY "Users can insert own recitations"
  ON public.recitation_attempts FOR INSERT
  WITH CHECK (auth.uid() = user_id);

-- ============================================================================
-- FIQH QUESTIONS
-- ============================================================================
CREATE TABLE IF NOT EXISTS public.fiqh_questions (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id uuid REFERENCES auth.users ON DELETE CASCADE NOT NULL,
  question text NOT NULL,
  answer text,
  madhab text DEFAULT 'hanafi',
  sources text,
  created_at timestamp with time zone DEFAULT now()
);

-- RLS for fiqh questions
ALTER TABLE public.fiqh_questions ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can view own questions"
  ON public.fiqh_questions FOR SELECT
  USING (auth.uid() = user_id);

CREATE POLICY "Users can insert own questions"
  ON public.fiqh_questions FOR INSERT
  WITH CHECK (auth.uid() = user_id);

-- ============================================================================
-- STORAGE BUCKETS
-- ============================================================================

-- Create storage bucket for recitation recordings
-- Note: This needs to be run in Supabase dashboard or via storage API
-- INSERT INTO storage.buckets (id, name, public) 
-- VALUES ('quran-recordings', 'quran-recordings', false);

-- RLS for storage
-- CREATE POLICY "Users can upload own recordings"
--   ON storage.objects FOR INSERT
--   WITH CHECK (bucket_id = 'quran-recordings' AND auth.uid()::text = (storage.foldername(name))[1]);

-- CREATE POLICY "Users can view own recordings"
--   ON storage.objects FOR SELECT
--   USING (bucket_id = 'quran-recordings' AND auth.uid()::text = (storage.foldername(name))[1]);
