-- IMANOS DATABASE SCHEMA (PRODUCTION-READY)
-- This script is idempotent and can be run multiple times safely

-- 1. PROFILES Table
CREATE TABLE IF NOT EXISTS public.profiles (
  id uuid REFERENCES auth.users ON DELETE CASCADE NOT NULL PRIMARY KEY,
  full_name text,
  avatar_url text,
  madhab text DEFAULT 'hanafi',
  arabic_level text,
  primary_goal text,
  daily_goal_minutes integer DEFAULT 10,
  updated_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 2. QURAN VERSE PROGRESS Table
CREATE TABLE IF NOT EXISTS public.quran_verse_progress (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id uuid REFERENCES auth.users ON DELETE CASCADE NOT NULL,
  surah integer NOT NULL,
  ayah integer NOT NULL,
  completed_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
  UNIQUE(user_id, surah, ayah)
);

-- 3. RECITATION ATTEMPTS Table
CREATE TABLE IF NOT EXISTS public.recitation_attempts (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id uuid REFERENCES auth.users ON DELETE CASCADE NOT NULL,
  surah integer NOT NULL,
  ayah integer NOT NULL,
  feedback jsonb,
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 4. FIQH QUESTIONS Table
CREATE TABLE IF NOT EXISTS public.fiqh_questions (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id uuid REFERENCES auth.users ON DELETE CASCADE NOT NULL,
  question text NOT NULL,
  answer jsonb,
  madhab text,
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- ENABLE ROW LEVEL SECURITY
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.quran_verse_progress ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.recitation_attempts ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.fiqh_questions ENABLE ROW LEVEL SECURITY;

-- RLS POLICIES (Idempotent)
DO $$ 
BEGIN
  -- Profiles
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies WHERE tablename = 'profiles' AND policyname = 'Users can manage own profile'
  ) THEN
    CREATE POLICY "Users can manage own profile" ON public.profiles
      FOR ALL USING (auth.uid() = id);
  END IF;

  -- Quran Progress
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies WHERE tablename = 'quran_verse_progress' AND policyname = 'Users can manage own progress'
  ) THEN
    CREATE POLICY "Users can manage own progress" ON public.quran_verse_progress
      FOR ALL USING (auth.uid() = user_id);
  END IF;

  -- Recitation Attempts
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies WHERE tablename = 'recitation_attempts' AND policyname = 'Users can manage own attempts'
  ) THEN
    CREATE POLICY "Users can manage own attempts" ON public.recitation_attempts
      FOR ALL USING (auth.uid() = user_id);
  END IF;

  -- Fiqh Questions
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies WHERE tablename = 'fiqh_questions' AND policyname = 'Users can manage own questions'
  ) THEN
    CREATE POLICY "Users can manage own questions" ON public.fiqh_questions
      FOR ALL USING (auth.uid() = user_id);
  END IF;
END $$;

-- AUTOMATIC PROFILE CREATION ON SIGNUP (Production-Ready)
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS trigger 
SECURITY DEFINER
SET search_path = public
LANGUAGE plpgsql
AS $$
BEGIN
  INSERT INTO public.profiles (id, full_name, avatar_url)
  VALUES (
    new.id,
    COALESCE(new.raw_user_meta_data->>'full_name', 'New User'),
    new.raw_user_meta_data->>'avatar_url'
  )
  ON CONFLICT (id) DO UPDATE
  SET 
    full_name = COALESCE(EXCLUDED.full_name, public.profiles.full_name),
    avatar_url = COALESCE(EXCLUDED.avatar_url, public.profiles.avatar_url),
    updated_at = now();
  
  RETURN new;
EXCEPTION
  WHEN OTHERS THEN
    -- Log error but don't fail the signup
    RAISE WARNING 'Error creating profile for user %: %', new.id, SQLERRM;
    RETURN new;
END;
$$;

-- Create trigger (idempotent)
DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW 
  EXECUTE FUNCTION public.handle_new_user();

-- Grant permissions
GRANT ALL ON public.profiles TO authenticated, service_role;
GRANT ALL ON public.quran_verse_progress TO authenticated, service_role;
GRANT ALL ON public.recitation_attempts TO authenticated, service_role;
GRANT ALL ON public.fiqh_questions TO authenticated, service_role;

-- Grant sequence permissions
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO authenticated, service_role;
