-- IMANOS DATABASE SCHEMA (SUPABASE)
-- Run this in the Supabase SQL Editor to sync your backend.

-- 1. PROFILES Table
-- Stores user metadata and onboarding preferences.
CREATE TABLE IF NOT EXISTS profiles (
  id uuid REFERENCES auth.users ON DELETE CASCADE NOT NULL PRIMARY KEY,
  full_name text,
  avatar_url text,
  madhab text DEFAULT 'hanafi',
  arabic_level text,
  primary_goal text,
  daily_goal_minutes integer DEFAULT 10,
  updated_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 2. QURAN VERSE PROGRESS Table
-- Tracks which verses have been marked as complete.
CREATE TABLE IF NOT EXISTS quran_verse_progress (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id uuid REFERENCES auth.users ON DELETE CASCADE NOT NULL,
  surah integer NOT NULL,
  ayah integer NOT NULL,
  completed_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
  UNIQUE(user_id, surah, ayah)
);

-- 3. RECITATION ATTEMPTS Table
-- Stores history of practice sessions and AI feedback.
CREATE TABLE IF NOT EXISTS recitation_attempts (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id uuid REFERENCES auth.users ON DELETE CASCADE NOT NULL,
  surah integer NOT NULL,
  ayah integer NOT NULL,
  feedback jsonb,
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 4. FIQH QUESTIONS Table
-- Stores user questions and AI-generated answers.
CREATE TABLE IF NOT EXISTS fiqh_questions (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id uuid REFERENCES auth.users ON DELETE CASCADE NOT NULL,
  question text NOT NULL,
  answer jsonb,
  madhab text,
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- ENABLE ROW LEVEL SECURITY
ALTER TABLE profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE quran_verse_progress ENABLE ROW LEVEL SECURITY;
ALTER TABLE recitation_attempts ENABLE ROW LEVEL SECURITY;
ALTER TABLE fiqh_questions ENABLE ROW LEVEL SECURITY;

-- RLS POLICIES (Privacy First)

-- Profiles
CREATE POLICY "Users can manage own profile" ON profiles
  FOR ALL USING (auth.uid() = id);

-- Quran Progress
CREATE POLICY "Users can manage own progress" ON quran_verse_progress
  FOR ALL USING (auth.uid() = user_id);

-- Recitation Attempts
CREATE POLICY "Users can manage own attempts" ON recitation_attempts
  FOR ALL USING (auth.uid() = user_id);

-- Fiqh Questions
CREATE POLICY "Users can manage own questions" ON fiqh_questions
  FOR ALL USING (auth.uid() = user_id);

-- AUTOMATIC PROFILE CREATION ON SIGNUP
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS trigger AS $$
BEGIN
  INSERT INTO public.profiles (id, full_name, avatar_url)
  VALUES (new.id, new.raw_user_meta_data->>'full_name', new.raw_user_meta_data->>'avatar_url');
  RETURN new;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Cleanup existing trigger to avoid duplicates
DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;

CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();
